"""make_item_date_nullable

Revision ID: 269d6a28e4be
Revises: 365bd1dc5a76
Create Date: 2026-04-08 17:41:46.944293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '269d6a28e4be'
down_revision: Union[str, Sequence[str], None] = '365bd1dc5a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workaround_obhhodnoilistzaiavlenieitem', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workaround_obhhodnoilistzaiavlenieitem', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
