"""добавление бд с отделами departmet

Revision ID: 365bd1dc5a76
Revises: a1b2c3d4e5f6
Create Date: 2026-04-07 16:26:45.992269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365bd1dc5a76'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workaround_department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('workaround_obhhodnoilistzaiavlenie', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('workaround_obhhodnoilistzaiavlenie', 'student_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('workaround_obhhodnoilistzaiavlenie_student_id_17798cdc'), table_name='workaround_obhhodnoilistzaiavlenie')
    op.drop_constraint(op.f('workaround_obhhodnoi_student_id_17798cdc_fk_workaroun'), 'workaround_obhhodnoilistzaiavlenie', type_='foreignkey')
    op.create_foreign_key(None, 'workaround_obhhodnoilistzaiavlenie', 'workaround_student', ['student_id'], ['id'], ondelete='CASCADE')
    op.add_column('workaround_obhhodnoilistzaiavlenieitem', sa.Column('department_id', sa.Integer(), nullable=False))
    op.alter_column('workaround_obhhodnoilistzaiavlenieitem', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.alter_column('workaround_obhhodnoilistzaiavlenieitem', 'statement_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('workaround_obhhodnoilistzaiavlenieitem', 'staff_worker_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.drop_index(op.f('workaround_obhhodnoilistzaiavlenieitem_staff_worker_id_eda7f11c'), table_name='workaround_obhhodnoilistzaiavlenieitem')
    op.drop_index(op.f('workaround_obhhodnoilistzaiavlenieitem_statement_id_bcb52c94'), table_name='workaround_obhhodnoilistzaiavlenieitem')
    op.drop_constraint(op.f('workaround_obhhodnoi_staff_worker_id_eda7f11c_fk_workaroun'), 'workaround_obhhodnoilistzaiavlenieitem', type_='foreignkey')
    op.drop_constraint(op.f('workaround_obhhodnoi_statement_id_bcb52c94_fk_workaroun'), 'workaround_obhhodnoilistzaiavlenieitem', type_='foreignkey')
    op.create_foreign_key(None, 'workaround_obhhodnoilistzaiavlenieitem', 'workaround_staffworker', ['staff_worker_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'workaround_obhhodnoilistzaiavlenieitem', 'workaround_obhhodnoilistzaiavlenie', ['statement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workaround_obhhodnoilistzaiavlenieitem', 'workaround_department', ['department_id'], ['id'], ondelete='CASCADE')
    op.add_column('workaround_staffworker', sa.Column('department_id', sa.Integer(), nullable=False))
    op.alter_column('workaround_staffworker', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.create_foreign_key(None, 'workaround_staffworker', 'workaround_department', ['department_id'], ['id'], ondelete='CASCADE')
    op.alter_column('workaround_student', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workaround_student', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_constraint(None, 'workaround_staffworker', type_='foreignkey')
    op.alter_column('workaround_staffworker', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_column('workaround_staffworker', 'department_id')
    op.drop_constraint(None, 'workaround_obhhodnoilistzaiavlenieitem', type_='foreignkey')
    op.drop_constraint(None, 'workaround_obhhodnoilistzaiavlenieitem', type_='foreignkey')
    op.drop_constraint(None, 'workaround_obhhodnoilistzaiavlenieitem', type_='foreignkey')
    op.create_foreign_key(op.f('workaround_obhhodnoi_statement_id_bcb52c94_fk_workaroun'), 'workaround_obhhodnoilistzaiavlenieitem', 'workaround_obhhodnoilistzaiavlenie', ['statement_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(op.f('workaround_obhhodnoi_staff_worker_id_eda7f11c_fk_workaroun'), 'workaround_obhhodnoilistzaiavlenieitem', 'workaround_staffworker', ['staff_worker_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index(op.f('workaround_obhhodnoilistzaiavlenieitem_statement_id_bcb52c94'), 'workaround_obhhodnoilistzaiavlenieitem', ['statement_id'], unique=False)
    op.create_index(op.f('workaround_obhhodnoilistzaiavlenieitem_staff_worker_id_eda7f11c'), 'workaround_obhhodnoilistzaiavlenieitem', ['staff_worker_id'], unique=False)
    op.alter_column('workaround_obhhodnoilistzaiavlenieitem', 'staff_worker_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('workaround_obhhodnoilistzaiavlenieitem', 'statement_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('workaround_obhhodnoilistzaiavlenieitem', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_column('workaround_obhhodnoilistzaiavlenieitem', 'department_id')
    op.drop_constraint(None, 'workaround_obhhodnoilistzaiavlenie', type_='foreignkey')
    op.create_foreign_key(op.f('workaround_obhhodnoi_student_id_17798cdc_fk_workaroun'), 'workaround_obhhodnoilistzaiavlenie', 'workaround_student', ['student_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index(op.f('workaround_obhhodnoilistzaiavlenie_student_id_17798cdc'), 'workaround_obhhodnoilistzaiavlenie', ['student_id'], unique=False)
    op.alter_column('workaround_obhhodnoilistzaiavlenie', 'student_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('workaround_obhhodnoilistzaiavlenie', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1))
    op.drop_table('workaround_department')
    # ### end Alembic commands ###
