"""add auth fields

Revision ID: 5e69b7b2986b
Revises: 269d6a28e4be
Create Date: 2026-04-10 20:16:25.202059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e69b7b2986b'
down_revision: Union[str, Sequence[str], None] = '269d6a28e4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### Добавляем поля в workaround_student ###
    op.add_column('workaround_student', sa.Column('sso_id', sa.String(length=100), nullable=True))
    op.add_column('workaround_student', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('workaround_student', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workaround_student', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('workaround_student', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_workaround_student_sso_id'), 'workaround_student', ['sso_id'], unique=True)
    op.create_unique_constraint(None, 'workaround_student', ['username'])

    # ### Добавляем поля в workaround_staffworker ###
    op.add_column('workaround_staffworker', sa.Column('sso_id', sa.String(length=100), nullable=True))
    op.add_column('workaround_staffworker', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('workaround_staffworker', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workaround_staffworker', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('workaround_staffworker', sa.Column('password_hash', sa.String(length=255), nullable=True))

    # === ИСПРАВЛЕНИЕ: сначала nullable=True ===
    op.add_column('workaround_staffworker', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.add_column('workaround_staffworker', sa.Column('is_superuser', sa.Boolean(), nullable=True))

    # Заполняем существующие записи значениями по умолчанию
    op.execute("UPDATE workaround_staffworker SET is_staff = FALSE WHERE is_staff IS NULL")
    op.execute("UPDATE workaround_staffworker SET is_superuser = FALSE WHERE is_superuser IS NULL")

    # Теперь делаем NOT NULL
    op.alter_column('workaround_staffworker', 'is_staff', nullable=False)
    op.alter_column('workaround_staffworker', 'is_superuser', nullable=False)

    op.create_index(op.f('ix_workaround_staffworker_sso_id'), 'workaround_staffworker', ['sso_id'], unique=True)
    op.create_unique_constraint(None, 'workaround_staffworker', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workaround_student', type_='unique')
    op.drop_index(op.f('ix_workaround_student_sso_id'), table_name='workaround_student')
    op.drop_column('workaround_student', 'password_hash')
    op.drop_column('workaround_student', 'username')
    op.drop_column('workaround_student', 'last_login')
    op.drop_column('workaround_student', 'email')
    op.drop_column('workaround_student', 'sso_id')

    op.drop_constraint(None, 'workaround_staffworker', type_='unique')
    op.drop_index(op.f('ix_workaround_staffworker_sso_id'), table_name='workaround_staffworker')
    op.drop_column('workaround_staffworker', 'is_superuser')
    op.drop_column('workaround_staffworker', 'is_staff')
    op.drop_column('workaround_staffworker', 'password_hash')
    op.drop_column('workaround_staffworker', 'username')
    op.drop_column('workaround_staffworker', 'last_login')
    op.drop_column('workaround_staffworker', 'email')
    op.drop_column('workaround_staffworker', 'sso_id')
    # ### end Alembic commands ###