# Generated by Django 6.0.3 on 2026-04-03 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObhhodnoiListZaiavlenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_status', models.IntegerField(choices=[(0, 'Не подписано'), (1, 'Подписано'), (2, 'Долг')], default=0, verbose_name='Общий статус')),
            ],
        ),
        migrations.CreateModel(
            name='StaffWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО Сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО Студента')),
            ],
        ),
        migrations.CreateModel(
            name='ObhhodnoiListZaiavlenieItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.BooleanField(default=False, verbose_name='Долг')),
                ('debt_comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('status', models.IntegerField(choices=[(0, 'Не подписано'), (1, 'Подписано'), (2, 'Долг')], default=0, verbose_name='Статус пункта')),
                ('date', models.DateTimeField(auto_now=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_statuses', to='workaround.obhhodnoilistzaiavlenie')),
                ('staff_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workaround.staffworker', verbose_name='Сотрудник')),
            ],
        ),
        migrations.AddField(
            model_name='obhhodnoilistzaiavlenie',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workaround.student', verbose_name='Студент'),
        ),
    ]
